### ISSUE TITLE
Epic for Displaying OBv3 Identity Object - LCW & VerifierPlus

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#513]
The OpenBadges Identity Object: https://1edtech.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.identityobject.class

contains credential subject related identity information. 1EdTech recently added name to this list of potential values:
https://1edtech.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.identifiertypeenum.class

- [ ] Decide which values will be displayed
- [ ] Create test badges containing those choices as non-hashed
- [ ] Create test badges containing those choices as hashed
- [ ] Create issue for display in LCW
- [ ] Create issue for display in VerifierPlus

**Comment by alexfigtree** [comment]
Question for discussion: Do we want to add all open badges fields in the wallet? Why/how?

**Comment by kayaelle** [comment]
Revisiting this issue as part of revising Credential display and adding alignment object. New issues will replace this one. TBD.

**Comment by alexfigtree** [comment]
@kayaelle Re: alignment object, can reference this issue: https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/681
