### ISSUE TITLE
[EPIC] VC CHAPI Playground issues to new version of signature suite 

### ISSUE THREAD

**Issue by alexfigtree** [digitalcredentials/learner-credential-wallet#611]
**Is your feature request related to a problem? Please describe.**
VC CHAPI Playground issues credential to new version of signature suite - needs fix/update

- [ ] ID signature suite we want to support
- [ ] Add support for suite
- [ ] Add support for libraries in wallet, issuer, and verifier

**Comment by kayaelle** [comment]
@alexfigtree - is it possible this issue is the same as #656 ?

**Comment by alexfigtree** [comment]
Duplicate of https://github.com/openwallet-foundation-labs/learner-credential-wallet/issues/656, closing
