### ISSUE TITLE
[EPIC] Feature flags

### ISSUE THREAD

**Issue by alexfigtree** [digitalcredentials/learner-credential-wallet#613]
Set up feature flags for LCW:

- [ ] Password prompt at wallet setup: https://github.com/digitalcredentials/learner-credential-wallet/issues/572
- [ ] Registering Wallet with browser at wallet setup: https://github.com/digitalcredentials/learner-credential-wallet/issues/573
- [ ] Dark mode: https://github.com/digitalcredentials/learner-credential-wallet/issues/574

- [ ] Adding to linkedin
- [ ] Profiles - each corresponding to a did

**Comment by kayaelle** [comment]
Do we want to do any feature flags as part of spitshine?

**Comment by alexfigtree** [comment]
We're leaving this issue as out of scope for spit shine
